const CertificateItems = [
  {
    name: "Developer Certificate",
    icon: "ri-code-s-slash-line",
    items: [
      {
        name: "MEMBUAT APLIKASI MOBILE EDUKASI",
        publisher:
          "Direktorat Jenderal Pendidikan Tinggi, Riset dan Teknologi Kemdikbudristek",
        credential: "2260/J6.3/TI/2021",
        year: "September 2021",
        ref: "",
      },
      {
        name: "IAII PROFISIENSI DATABASE SYSTEM",
        publisher: "Ikatan Ahli Informatika Indonesia",
        credential: "9AJOUEFZcg",
        year: "Jul 2023",
        ref: "",
      },
      {
        name: "Sertifikat Kelas Belajar Dasar HTML",
        publisher: "Codepolitan",
        credential: "WRDYSEJ",
        year: "February 2024 - February 2027",
        ref: "https://codepolitan.com/c/WRDYSEJ",
      },
      {
        name: "Sertifikat Kelas Pengenalan Database Menggunakan MySQL",
        publisher: "Codepolitan",
        credential: "8ZBFLHU",
        year: "March 2024 - March 2027",
        ref: "https://codepolitan.com/c/8ZBFLHU",
      },
      {
        name: "Sertifikat Kelas Laravel 8x Fundamental",
        publisher: "Codepolitan",
        credential: "WQ6YAHC",
        year: "March 2024 - March 2027",
        ref: "https://codepolitan.com/c/WQ6YAHC",
      },
      {
        name: "Sertifikat Kelas Konsep Dasar Pemrograman Berorientasi Objek di PHP",
        publisher: "Codepolitan",
        credential: "OBWK3WA",
        year: "March 2024 - March 2027",
        ref: "https://codepolitan.com/c/OBWK3WA",
      },
      {
        name: "Sertifikat Kelas Belajar Pemrograman PHP",
        publisher: "Codepolitan",
        credential: "LVQJR9H",
        year: "March 2024 - March 2027",
        ref: "https://codepolitan.com/c/LVQJR9H",
      },
      {
        name: "Sertifikat Kelas Belajar JavaScript",
        publisher: "Codepolitan",
        credential: "PZH2RUM",
        year: "March 2024 - March 2027",
        ref: "https://codepolitan.com/c/PZH2RUM",
      },
      {
        name: "Sertifikat Kelas Belajar JQuery Dasar",
        publisher: "Codepolitan",
        credential: "1GVBNFL",
        year: "March 2024 - March 2027",
        ref: "https://codepolitan.com/c/1GVBNFL",
      },
      {
        name: "Sertifikat Kelas Belajar Framework Laravel Dasar",
        publisher: "Codepolitan",
        credential: "FUWLCAM",
        year: "March 2024 - March 2027",
        ref: "https://codepolitan.com/c/FUWLCAM",
      },
      {
        name: "Sertifikat Kelas Belajar Dasar CSS",
        publisher: "Codepolitan",
        credential: "RPF3OHN",
        year: "March 2024 - March 2027",
        ref: "https://codepolitan.com/c/RPF3OHN",
      },
      {
        name: "Sertifikat Kelas Belajar Bootstrap CSS Framework",
        publisher: "Codepolitan",
        credential: "XEPR9YL",
        year: "March 2024 - March 2027",
        ref: "https://codepolitan.com/c/XEPR9YL",
      },
      {
        name: "Sertifikat Kelas Penggunaan Database MySQL pada Pemrograman PHP",
        publisher: "Codepolitan",
        credential: "6BAGEU9",
        year: "July 2024 - July 2027",
        ref: "https://codepolitan.com/c/6BAGEU9",
      },
      {
        name: "Sertifikat Kelas Panduan Awal Menjadi Fullstack Web Developer",
        publisher: "Codepolitan",
        credential: "TWXA4PN",
        year: "July 2024 - July 2027",
        ref: "https://codepolitan.com/c/TWXA4PN",
      },
      {
        name: "Sertifikat Kelas Membuat Landing Page Website dengan Bootstrap 4",
        publisher: "Codepolitan",
        credential: "YWO2FBS",
        year: "July 2024 - July 2027",
        ref: "https://codepolitan.com/c/YWO2FBS",
      },
      {
        name: "Skilvul SkilBadge - React Dasar",
        publisher: "Skilvul",
        credential: "",
        year: "Augst 2024",
        ref: "",
      },
    ],
  },
  {
    name: "Cyber Security Certificate",
    icon: "ri-bug-line",
    items: [
      {
        name: "WEB HACKING FOR BEGINERS",
        publisher: "Udemy",
        credential: "UC-74223810-8881-462c-b893-d8f0533d2d48",
        year: "November 2021",
        ref: "",
      },
      {
        name: "Network Ethical Hacking For Beginners (Kali-Hands-on)",
        publisher: "Udemy",
        credential: "UC-7015f9a0-adf0-4c88-a72e-6f56fb6196ee",
        year: "November 2021",
        ref: "",
      },
      {
        name: "LKS WILKER 4 CYBER SECURITY Field",
        publisher:
          "Direktorat Jenderal Pendidikan Tinggi, Riset dan Teknologi Kemdikbudristek",
        credential: "08/MKKS/Wilker4/II/2022",
        year: "February 2021",
        ref: "",
      },
      {
        name: "Sertifikat peserta Gemastik : Cyber Security",
        publisher:
          "Direktorat Jenderal Pendidikan Tinggi, Riset dan Teknologi Kemdikbudristek",
        credential: "001/DIV 2/GXV/2022",
        year: "November 2022",
        ref: "",
      },
    ],
  },
  {
    name: "Graphic Design and Video Editing Certificate",
    icon: "ri-video-on-line",
    items: [
      {
        name: "Siswa Cerdas Kreatif ( Video Editing ) ",
        publisher: "SMKN 1 Donorojo",
        credential: "",
        year: "October 2020",
        ref: "",
      },
      {
        name: "PIlfatek Video Editing Certificate",
        publisher: "Universitas Widyagama Malang",
        credential: "",
        year: "March 2021",
        ref: "",
      },
      {
        name: "Lomba Poster Nasional Certificate",
        publisher: "Universitas Trilogi",
        credential: "",
        year: "August 2021",
        ref: "",
      },
    ],
  },
  {
    name: "Cloud Computing Certificate",
    icon: "ri-cloud-line",
    items: [
      {
        name: "CSE Alibaba Cloud",
        publisher: "Alibaba Cloud",
        credential: "ACCD0119700100008323",
        year: "Feb 2024 - Feb 2027",
        ref: "",
      },
      {
        name: "Apsara Clouder - Cloud Computing ",
        publisher: "Alibaba Cloud",
        credential: "ACFC03240400115288",
        year: "Apr 2024 - Apr 2027",
        ref: "",
      },
      {
        name: "ACA Cloud Computing Certification",
        publisher: "Alibaba Cloud",
        credential: "IACA01240500117661L",
        year: "May 2024 - May 2027",
        ref: "https://aliyun-aps-cloud-public.oss-cn-hangzhou.aliyuncs.com/img_c648685440615bbdeee57d180482ad00.jpg",
      },
      {
        name: "ACP Cloud Computing Certification",
        publisher: "Alibaba Cloud",
        credential: "IACP01240600124391",
        year: "June 2024 - June 2027",
        ref: "https://edu.alibabacloud.com/clouder/my/clouderpackage/?type=acp&clouder_certificat_id=123064",
      },
    ],
  },
  {
    name: "IT Support Certificate",
    icon: "ri-computer-line",
    items: [
      {
        name: "GOOGLE IT : Keamanan IT: Pertahanan terhadap Kejahatan Digital Certificate",
        publisher: "Coursera",
        credential: "TGSY2U3JGYV5",
        year: "July 2022",
        ref: "https://coursera.org/verify/TGSY2U3JGYV5",
      },
      {
        name: "GOOGLE IT : Dasar-Dasar Dukungan Teknis Certificate",
        publisher: "Coursera",
        credential: "VFKRL5E9M8XX",
        year: "July 2022",
        ref: "https://coursera.org/verify/VFKRL5E9M8XX",
      },
      {
        name: "GOOGLE IT : Seluk Beluk Jaringan Komputer Certificate",
        publisher: "Coursera",
        credential: "9CUCECENS2N3",
        year: "August 2022",
        ref: "https://coursera.org/verify/9CUCECENS2N3",
      },
    ],
  },
  {
    name: "Network Administrator Certificate",
    icon: "ri-global-line",
    items: [
      {
        name: "MTCNA",
        publisher: "MikroTik",
        credential: "2104NA6671",
        year: "April 2021",
        ref: "",
      },
    ],
  },
  {
    name: "Other Certificate",
    icon: "ri-more-fill",
    items: [
      {
        name: "Certificate Of Competency Assessment",
        publisher: "SMKN 1 DONOROJO",
        credential: "",
        year: "2022",
        ref: "",
      },
      {
        name: "SEMINAR WAJIB ENTREPRENEUR",
        publisher: "Universitas Bina Sarana Informatika",
        credential: "",
        year: "2024",
        ref: "",
      },
      {
        name: "Google Profil Bisnis dan E-Commerce (Digital Entrepreneurship Academy)",
        publisher: "Digital Talent Scholarship",
        credential: "",
        year: "June 2023",
        ref: "https://digitalent.kominfo.go.id/cek-sertifikat",
      },
      {
        name: "Software Quality Assurance",
        publisher: "Tanjung Mulia Informatika",
        credential: "",
        year: "July 2023",
        ref: "",
      },
    ],
  },
];

export default CertificateItems;
